{
 "title": "SOLDR VXAPI",
 "tags": [ "SOLDR" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "api_server_id", "query": { "query": "label_values(api_server_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Server resources utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage_percent{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}"
    }
   ]
  },
  {
   "title": "VIRT memory usage bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}"
    }
   ]
  },
  {
   "title": "RSS memory usage bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}"
    }
   ]
  },
  {
   "title": "Golang runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "go_stack_inuse_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_stack_inuse_bytes{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}"
    }
   ]
  },
  {
   "title": "go_stack_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_stack_sys_bytes{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}"
    }
   ]
  },
  {
   "title": "go_cgo_calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(go_cgo_calls{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "go_goroutines{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}"
    }
   ]
  },
  {
   "title": "go_pause_gc_total_nanosec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(go_pause_gc_total_nanosec{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "go_heap_objects_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_heap_objects_bytes{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}"
    }
   ]
  },
  {
   "title": "go_heap_allocs_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_heap_allocs_bytes{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}"
    }
   ]
  },
  {
   "title": "rate(go_total_allocs_bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(go_total_allocs_bytes{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "go_heap_objects_counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 34 },
   "targets": [
    {
     "expr": "go_heap_objects_counter{api_server_id=~\"$api_server_id\", service_name=\"vxapi\"}"
    }
   ]
  }
 ]
}