{
 "title": "SOLDR VXModules",
 "tags": [ "SOLDR" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "agent_id", "label": "agent_id", "query": { "query": "label_values(agent_id)" } },
   { "name": "group_id", "query": { "query": "label_values(group_id)" } },
   { "name": "policy_id", "query": { "query": "label_values(policy_id)" } },
   { "name": "server_id", "query": { "query": "label_values(server_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Syslog module",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server module memory usage bytes ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "syslog_server_mem_usage{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"syslog\", component=\"lua_state\"}"
      },
      {
       "expr": "sum by (component)(syslog_server_mem_usage{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"syslog\", component=\"lua_state\"})",
       "legendFormat": "Sum module memory usage bytes"
      }
     ]
    },
    {
     "title": "Agent module memory usage bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "syslog_agent_mem_usage{agent_id=~\"$agent_id\", module_name=\"syslog\", component=\"lua_state\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}"
      }
     ]
    },
    {
     "title": "Server module queue count events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "syslog_server_events_queue_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"syslog\", component=\"lua_state\"}"
      }
     ]
    },
    {
     "title": "Sum events server send per interval",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(syslog_server_events_send_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"syslog\", component=\"lua_state\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Sum events server recv per interval",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(syslog_server_events_recv_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"syslog\", component=\"lua_state\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Server module send/recv bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(syslog_server_events_send_size{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      },
      {
       "expr": "rate(syslog_server_events_recv_size{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Server module send/recv events counter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "rate(syslog_server_events_send_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      },
      {
       "expr": "rate(syslog_server_events_recv_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Agent module send bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(syslog_agent_events_send_size{agent_id=~\"$agent_id\", module_name=\"syslog\", component=\"lua_state\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Agent module send events counter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "rate(syslog_agent_events_send_count{agent_id=~\"$agent_id\", module_name=\"syslog\", component=\"lua_state\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Server module events drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "rate(syslog_server_events_drop{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"syslog\", component=\"lua_state\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Agent module events drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "rate(syslog_agent_events_drop{agent_id=~\"$agent_id\", module_name=\"syslog\", component=\"lua_state\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Correlator module",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "Agent module memory usage bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "corr_agent_mem_usage{agent_id=~\"$agent_id\", module_name=~\"correlator|correlator_linux\", component=\"lua_state\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}"
    }
   ]
  },
  {
   "title": "Agent module recv events counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "rate(corr_agent_events_recv_count{agent_id=~\"$agent_id\", module_name=~\"correlator|correlator_linux\", component=\"lua_state\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Agent module recv bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(corr_agent_events_recv_size{agent_id=~\"$agent_id\", module_name=~\"correlator|correlator_linux\", component=\"lua_state\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Agent events count per interval",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(corr_agent_events_recv_count{agent_id=\"$agent_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=~\"correlator|correlator_linux\", component=\"lua_state\"}[$__range])"
    }
   ]
  },
  {
   "title": "Agent module events drop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "rate(corr_agent_events_drop{agent_id=\"$agent_id\", module_name=~\"correlator|correlator_linux\", component=\"lua_state\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Windows event log module",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server module memory usage bytes ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "wel_server_mem_usage{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"wineventlog\", component=\"lua_state\"}"
      },
      {
       "expr": "sum by (component)(wel_server_mem_usage{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"wineventlog\", component=\"lua_state\"})",
       "legendFormat": "Sum memory usage by all Lua states on server"
      }
     ]
    },
    {
     "title": "Agent module memory usage bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "wel_agent_mem_usage{agent_id=~\"$agent_id\", module_name=\"wineventlog\", component=\"lua_state\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}"
      }
     ]
    },
    {
     "title": "Server module queue count events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "wel_server_events_queue_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"wineventlog\", component=\"lua_state\"}"
      }
     ]
    },
    {
     "title": "Sum events server recv per interval",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(wel_server_events_recv_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"wineventlog\", component=\"lua_state\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Sum events server send per interval",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(wel_server_events_send_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"wineventlog\", component=\"lua_state\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Server module send/recv bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(wel_server_events_recv_size{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      },
      {
       "expr": "rate(wel_server_events_send_size{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Server module send/recv events counter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "rate(wel_server_events_recv_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      },
      {
       "expr": "rate(wel_server_events_send_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Agent module send bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(wel_agent_events_send_size{agent_id=~\"$agent_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Agent module send events counter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(wel_agent_events_send_count{agent_id=~\"$agent_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Server module events drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "rate(wel_server_events_drop{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"wineventlog\", component=\"lua_state\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Agent module events drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "wel_agent_events_drop{agent_id=~\"$agent_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Linux log files reader module",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server module memory usage bytes ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "frd_server_mem_usage{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"file_reader\", component=\"lua_state\"}"
      },
      {
       "expr": "sum by (component)(frd_server_mem_usage{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"file_reader\", component=\"lua_state\"})",
       "legendFormat": "Sum memory usage by all Lua states on server"
      }
     ]
    },
    {
     "title": "Agent module memory usage bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "frd_agent_mem_usage{agent_id=~\"$agent_id\", module_name=\"file_reader\", component=\"lua_state\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}"
      }
     ]
    },
    {
     "title": "Server module queue count events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "frd_server_events_queue_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"file_reader\", component=\"lua_state\"}"
      }
     ]
    },
    {
     "title": "Sum events server recv per interval",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(frd_server_events_recv_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"file_reader\", component=\"lua_state\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Sum events server send per interval",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(frd_server_events_send_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"file_reader\", component=\"lua_state\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Server module send/recv bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(frd_server_events_recv_size{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      },
      {
       "expr": "rate(frd_server_events_send_size{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Server module send/recv events counter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "rate(frd_server_events_recv_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\",module_name=\"file_reader\"}[$__rate_interval])"
      },
      {
       "expr": "rate(frd_server_events_send_count{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\",module_name=\"file_reader\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Agent module send bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(frd_agent_events_send_size{agent_id=~\"$agent_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Agent module send events counter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(frd_agent_events_send_count{agent_id=~\"$agent_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Server module events drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "rate(frd_server_events_drop{server_id=~\"$server_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\", module_name=\"file_reader\", component=\"lua_state\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Agent module events drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "frd_agent_events_drop{agent_id=~\"$agent_id\", group_id=~\"$group_id\", policy_id=~\"$policy_id\"}"
      }
     ]
    }
   ]
  }
 ]
}