{
 "title": "SOLDR VXProto",
 "tags": [ "SOLDR" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server_id", "query": { "query": "label_values(server_id)" } },
   { "name": "agent_id", "query": { "query": "label_values(agent_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Server send total packets count per interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(proto_send_num_packets{server_id=~\"$server_id\", service_name=\"vxserver\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total send/recv net bytes per interval",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(proto_send_net_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"}[$__range]))",
     "legendFormat": "Server send"
    },
    {
     "expr": "sum(increase(proto_recv_net_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"}[$__range]))",
     "legendFormat": "Server received"
    },
    {
     "expr": "sum(increase(proto_send_net_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"}[$__range]))",
     "legendFormat": "Agent send"
    },
    {
     "expr": "sum(increase(proto_recv_net_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"}[$__range]))",
     "legendFormat": "Agent received"
    }
   ]
  },
  {
   "title": "Total send/recv net bytes without compression per interval",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(proto_send_payload_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"}[$__range]))",
     "legendFormat": "Server send"
    },
    {
     "expr": "sum(increase(proto_recv_payload_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"}[$__range]))",
     "legendFormat": "Server received"
    },
    {
     "expr": "sum(increase(proto_send_payload_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"}[$__range]))",
     "legendFormat": "Agent send"
    },
    {
     "expr": "sum(increase(proto_recv_payload_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"}[$__range]))",
     "legendFormat": "Agent received"
    }
   ]
  },
  {
   "title": "Server recv total packets count per interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(proto_recv_num_packets{server_id=~\"$server_id\", service_name=\"vxserver\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Send packets counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(proto_send_num_packets{server_id=~\"$server_id\", service_name=\"vxserver\"}[$__rate_interval])"
    },
    {
     "expr": "rate(proto_send_num_packets{agent_id=~\"$agent_id\", service_name=\"vxagent\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Recv packets counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(proto_recv_num_packets{agent_id=~\"$agent_id\", service_name=\"vxagent\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Send net bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "delta(proto_send_net_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"})"
    },
    {
     "expr": "delta(proto_send_net_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"})"
    }
   ]
  },
  {
   "title": "Recv net bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "delta(proto_recv_net_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"})"
    },
    {
     "expr": "delta(proto_recv_net_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"})"
    }
   ]
  },
  {
   "title": "Send bytes without compression",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "delta(proto_send_payload_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"})"
    },
    {
     "expr": "delta(proto_send_payload_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"})"
    }
   ]
  },
  {
   "title": "Recv net bytes without compression",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "delta(proto_recv_payload_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"})"
    },
    {
     "expr": "delta(proto_recv_payload_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"})"
    }
   ]
  },
  {
   "title": "Send compression rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "proto_send_payload_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"} / proto_send_net_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"}"
    },
    {
     "expr": "proto_send_payload_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"} / proto_send_net_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"}"
    }
   ]
  },
  {
   "title": "Recv compression rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "proto_recv_payload_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"} / proto_recv_net_bytes{server_id=~\"$server_id\", service_name=\"vxserver\"}"
    },
    {
     "expr": "proto_recv_payload_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"} / proto_recv_net_bytes{agent_id=~\"$agent_id\", service_name=\"vxagent\"}"
    }
   ]
  }
 ]
}