extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: "0.0.0.0:8148"
      http:
  jaeger:
    protocols:
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
                  - targets: ['node-exporter.local:9100']
        - job_name: 'otel-elastic'
          scrape_interval: 10s
          static_configs:
                  - targets: ['elasticsearch-exporter.local:9114']
        - job_name: 'jaeger-collector'
          scrape_interval: 10s
          static_configs:
                  - targets: ['jaeger.local:14269']

processors:
  batch:
    timeout: 10s
    send_batch_size: 1000

exporters:
  logging:
    loglevel: error
  jaeger:
    endpoint: "jaeger.local:14250"
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: "http://victoriametrics.local:8428/api/v1/write"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp,  prometheus]
      processors: [batch]
      exporters: [logging, prometheusremotewrite]

  extensions: [health_check, pprof, zpages]
