# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: victoriametrics
  - name: Jaeger
  - name: Loki

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: VictoriaMetrics
    # <string, required> datasource type. Required
    type: prometheus
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <string> url
    url: http://victoriametrics.local:8428
    # <string> Deprecated, use secureJsonData.password
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true
    # additional parameters
    jsonData:
      manageAlerts: false
  - name: Jaeger
    # <string, required> datasource type. Required
    type: jaeger
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <string> url
    url: http://jaeger.local:16686
    # <string> Deprecated, use secureJsonData.password
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true
    # additional parameters
    jsonData:
      manageAlerts: false
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: Loki
        filterBySpanID: true
        filterByTraceID: true
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
        mappedTags:
          - key: otel.library.name
            value: service_name
  - name: Loki
    # <string, required> datasource type. Required
    type: loki
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <string> url
    url: http://loki.local:3100
    # <string> Deprecated, use secureJsonData.password
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true
    # additional parameters
    jsonData:
      maxLines: 1000
      manageAlerts: false
      derivedFields:
        - datasourceUid: Jaeger
          matcherRegex: "(?:\"traceid\"):\"(\\w+)\""
          name: traceid
          url: '$${__value.raw}'
          urlDisplayLabel: "Trace for this log"
